# Generated by Django 5.0 on 2023-12-12 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_alter_task_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='delete_at',
        ),
    ]
